### ISSUE TITLE
Manage Quick Ratio

### ISSUE THREAD

**Issue by phooda0718** [Mittal-Analytics/Screener.in#10]
Not able to change the quick ratio on screener.in, once selected. It shows Removing and just stops there. I've attached the screenshot for your reference.

![screener - manage quick ratio issue](https://cloud.githubusercontent.com/assets/17244544/13040925/37186152-d3d8-11e5-956f-81dbbe225601.png)

**Comment by pratyushmittal** [comment]
There was a error in backend. Fixed now.

**Comment by phooda0718** [comment]
Appreciate the quick fix. Thanks!
