### ISSUE TITLE
Many stocks not displayed in result of Query Builder

### ISSUE THREAD

**Issue by sandeshkamble** [Mittal-Analytics/Screener.in#100]
Hi,
I am noticing this for past few days now that many of the stocks are not displayed in result of query builder for very basic query as given below for an example.
Bharat Rasayan is having cmp 4100.00 and Market Cap of 1742.50
I created query as below:
Market Capitalization > 1600 AND
Current price >= 4000
This gives 19 hits but missing Bharat Rasayan. This scrip was resulted in one of my private screener but missing in the screener and hence tried to verify. Individual page works fine but query builder result do not show this one.
Whats the issue and by when will this get fixed?

**Comment by pratyushmittal** [comment]
Hi @sandeshkamble , thanks for detailed issue submission.

It has been fixed now.

Happy new year :).
