### ISSUE TITLE
Email Alert not working and cant find the link to create new Column

### ISSUE THREAD

**Issue by Techani20** [Mittal-Analytics/Screener.in#11]
Hello, 
Cant activate Alerts for new screens. Once the button is clicked, the button changes to "Procesing" and remains like that.

The second problem is I can seem to find the link to create a new Column formula. I guess it was located on the accounts/profile page but now cant seem to find it. 

Please help.

Thank you.

**Comment by pratyushmittal** [comment]
Fixed alerts for new screens in https://github.com/Mittal-Analytics/Screener.in/commit/e1794d1c239b936c88a45124b69e5e09b9c92aef .

Custom ratios will be back soon.

Thanks for reporting.
