### ISSUE TITLE
Query not responding when Net Profit and Interest (last 2 yr) being compared

### ISSUE THREAD

**Issue by anubhavit** [Mittal-Analytics/Screener.in#111]
Market Capitalization > 500 AND
Market Capitalization < 10000 AND
EPS latest quarter > 1.2 * EPS preceding year quarter   AND
EPS latest quarter > 0 AND
EPS last year  > 1.05 * EPS preceding year AND
EPS > 1.05 * EPS last year AND
Down from 52w high < 18 AND
Current ratio > 2 AND
EVEBITDA <= 20 AND
Profit growth 3Years > 22 AND
Return on equity >= 17 and 
Piotroski score >= 4 AND
PEG Ratio > 0 AND
PEG Ratio < 1.5 AND
Sales latest quarter > Sales preceding year quarter and 
Sales / Equity capital > 15 AND
Return on capital employed > 15 and 
Equity capital < 20 and 
Book value / Face value  > 5 AND
Net profit > Interest AND

> Net Profit last year > Interest last year  AND
> Net Profit preceding year > Interest preceding year

**Comment by pratyushmittal** [comment]
Hi @anubhavit , it seems to be working fine.
