### ISSUE TITLE
Sales Growth, Profit growth, etc shows NAN many times

### ISSUE THREAD

**Issue by luqmanshahid** [Mittal-Analytics/Screener.in#116]
Ashok leyland 3 years average profit growth is NAN.
many other parameter for different companies show NAN like ROE, Sales growth, Profit growth etc. which has nothing to do with loss.
Please fix this ASAP.

**Comment by pratyushmittal** [comment]
Hi @luqmanshahid , can you please share a screenshot.

**Comment by luqmanshahid** [comment]
The screenshot is attached.

**Comment by luqmanshahid** [comment]
The image is attached.

**Comment by luqmanshahid** [comment]
file:///C:/Users/lks658452/Documents/NAN%20Problem.jpg

**Comment by luqmanshahid** [comment]
![nan problem](https://user-images.githubusercontent.com/22763169/37695794-e4e91860-2cf7-11e8-85aa-85547d7d0994.jpg)

**Comment by luqmanshahid** [comment]
![nan problem2](https://user-images.githubusercontent.com/22763169/37695841-47b3d480-2cf8-11e8-9b98-9356ebf3c3d3.PNG)

**Comment by luqmanshahid** [comment]
See the last Column.

**Comment by luqmanshahid** [comment]
See the last Column.

**Comment by luqmanshahid** [comment]
Hello @pratyushmittal  please update on the issue.

**Comment by pratyushmittal** [comment]
Hi @luqmanshahid , while calculating Profit growths and other such ratios, we exclude extra-ordinary incomes. After excluding extra-ordinary income, these would have had losses in that year. This is the reason they are showing Nan.

Hope that helps.

**Comment by luqmanshahid** [comment]
Hello @pratyushmittal , I dont think this is the issue. because sales number are also showing NAN.
Their might be some calculation error, or the data input is not correct.

**Comment by pratyushmittal** [comment]
Hi @luqmanshahid,

I checked General Insurance and New India Assurance for debugging. In both cases the companies got listed very recently. Their 5 year old financial numbers are not available and that is why they are showing NaN. Hope that helps.
