### ISSUE TITLE
Cannot unsubscribe from watchlist alerts

### ISSUE THREAD

**Issue by shubhendusaurabh** [Mittal-Analytics/Screener.in#12]
I get following errors in my console on clicking the disable button
![screenr](https://cloud.githubusercontent.com/assets/1818387/13801456/eefb76b0-eb57-11e5-9902-a38f61dedf5b.PNG)

**Comment by pratyushmittal** [comment]
Thanks for reporting Shubhendu. Fixed in 4cfb3fcfc0e403c16d2a65b6248422bf98650cff.
