### ISSUE TITLE
Face value after split is not changed.

### ISSUE THREAD

**Issue by nirbhaypatil** [Mittal-Analytics/Screener.in#132]
Foods and Inns Split, Old FV Rs 10, New FV Rs 1, Announcement date: Feb 08, 2018, Ex-Split: Apr 19, 2018Record date: Apr 20, 2018, 20

Still this is not changed after one month.

**Comment by Parthgarg02** [comment]
Please do let us know if this problem still exists.

**Comment by nirbhaypatil** [comment]
As face value is 1 Rs now, closing this issue.
