### ISSUE TITLE
Consolidated Quarterly results for many companies not showing

### ISSUE THREAD

**Issue by luqmanshahid** [Mittal-Analytics/Screener.in#135]
Hi @pratyushmittal,
Consolidated Quarterly results for many companies not showing like HDFC Bank, YES Bank etc.
Please Resolve.

**Comment by Parthgarg02** [comment]
This is because those companies do not declare their consolidated quarterly results.

**Comment by luqmanshahid** [comment]
Hi @Parthgarg02,
Previous Quaterly results were there. How this quater its not thier.

**Comment by luqmanshahid** [comment]
Hi @Parthgarg02,
The consolidated quaterly results are their on their site. Please update it.

**Comment by Parthgarg02** [comment]
Please share the link of consolidated quarterly results, we will check and revert.

**Comment by luqmanshahid** [comment]
https://www.hul.co.in/Images/mq-2018-results_tcm1255-522301_en.pdf

**Comment by luqmanshahid** [comment]
https://www.screener.in/company/HINDUNILVR/consolidated
Quarterly Results Consolidated Figures is blank.

**Comment by Parthgarg02** [comment]
In the link provided by you the consolidated results for full year are available, which is also available on our website screener.in 
The consolidated quarterly results aren't provided from the company's end itself.

**Comment by luqmanshahid** [comment]
Please make consolidated results equal to standalone where they are not available.

**Comment by Parthgarg02** [comment]
Hi Shahid, we don't believe that would be a right thing to do. Also, all the companies will start publishing their quarterly numbers on consolidated basis soon: https://twitter.com/ashwinidamani/status/1008906482715222016

Hope that helps.

**Comment by luqmanshahid** [comment]
The quarterly sales, profit growth, etc for those companies are showing "NAN". These companies are getting filtered unnecessarily.

**Comment by pratyushmittal** [comment]
Hi Shahid,

Thanks for reporting this case. We have an algorithm to automatically detect the important set of numbers between standalone and consolidated. It should have picked standalone as default in cases such as HUL. We have fixed it and should reflect on the website over next few days.

Thanks.
