### ISSUE TITLE
npm start erroring out - Error: socket hang up

### ISSUE THREAD

**Issue by rishikeshm** [Mittal-Analytics/Screener.in#137]
I have cloned the repository https://github.com/Mittal-Analytics/Screener.in.git , and ran npm install, but when I try to start the application with "npm start" or "node server.js" and hitting the local url http://127.0.0.1:8000/ I am getting the below error in windows console.

Error: socket hang up
    at createHangUpError (_http_client.js:313:15)
    at Socket.socketOnEnd (_http_client.js:416:23)
    at Socket.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19) code: 'ECONNRESET'

Kindly help in resolving this issue and to get the application started locally.

**Comment by rishikeshm** [comment]
Any update on this issue ?

**Comment by aksingh11** [comment]
its the code being improved ? lots of data wrong  .

**Comment by pratyushmittal** [comment]
@rishikeshm We are working on a new release and this code might not work. We will update it soon.

**Comment by rishikeshm** [comment]
@pratyushmittal thank you for the update, please do let me know once you release the new code. Also do let me know how do I setup the application locally.
