### ISSUE TITLE
Error in tax calculation

### ISSUE THREAD

**Issue by iamshubh22** [Mittal-Analytics/Screener.in#28]
Tax is calculated by deducting some percentage amount from 'Profit before tax'. When this 'Profit before tax' is negative, tax is also coming out to be negative.

Example: 
![screenshot from 2016-07-06 00-57-58](https://cloud.githubusercontent.com/assets/13465950/16597194/401cd68c-4315-11e6-9d70-9c4536c5fbaf.png)

**Comment by pratyushmittal** [comment]
Hi @iamshubh22 ,

The tax is negative because company got the tax credit in 2014: http://www.bseindia.com/bseplus/AnnualReport/530073/5300730314.pdf#page=48

Hope that helps,
Pratyush
