### ISSUE TITLE
It doesn't load home page and giving an error of module not found.

### ISSUE THREAD

**Issue by sdavara** [Mittal-Analytics/Screener.in#3]
![screen shot 2015-11-27 at 6 42 34 pm](https://cloud.githubusercontent.com/assets/1996252/11441924/c03a43be-9536-11e5-9657-cdd699e62d82.png)

**Comment by pratyushmittal** [comment]
Hi Shailesh, is this on development server or the website? Also, which version of Chrome?

**Comment by sdavara** [comment]
It's on development server(when I try to run code locally). On the live site, I noticed login page shows 'register' page. It needs to fix, I also reported bug in bitbucket.

**Comment by pratyushmittal** [comment]
I have updated the module to ensure that the first built is compiled before starting the dev server. Can you please `git pull` and give it a retry?

**Comment by sdavara** [comment]
When I fire 'npm run' it gives below error in terminal:


ERROR in ./app/api.js
Module not found: Error: Cannot resolve module 'whatwg-fetch' in /Users/sd/Screener.in/app
 @ ./app/api.js 1:0-42

**Comment by pratyushmittal** [comment]
Ah, okay. Fixed the dependencies now. You will need to do `npm install` and then `npm run`.

**Comment by sdavara** [comment]
Now..

Lifecycle scripts included in screener:
  prestart
    webpack -d && (node server.js&)
  start
    webpack -d --watch
  test
    jest

available via `npm run-script`:
  build
    NODE_ENV=production webpack -p

**Comment by pratyushmittal** [comment]
Oh I meant `npm install` and then `npm start`.

**Comment by sdavara** [comment]
Yes, I followed that step and then above error.

**Comment by sdavara** [comment]
I believe to fix dependency and package's use 'npm-shrinkwrap'

**Comment by pratyushmittal** [comment]
I tried `git clone` then, `npm install` followed by `npm start` in a fresh directory. It is working fine at my end.

Can you please give it a re-try in a fresh directory? In case it persists, I can try to look into it over TeamViewer.

Thanks for pursuing,
Pratyush

**Comment by sdavara** [comment]
I tried in a new fresh directory and same error:

Lifecycle scripts included in screener:
  prestart
    webpack -d && (node server.js&)
  start
    webpack -d --watch
  test
    jest

available via `npm run-script`:
  build
    NODE_ENV=production webpack -p

FYI, my node version is : v5.1.0

**Comment by pratyushmittal** [comment]
The above should be the output of `npm run` as it only lists the available commands. You need to do `npm start`.

**Comment by sdavara** [comment]
Thanks Pratyush, It worked for me. I've also created a PR for you :) By the way, what have you used in back-end? Python?

**Comment by pratyushmittal** [comment]
Yup, backend is Django.

**Comment by pratyushmittal** [comment]
gg
