### ISSUE TITLE
Shareholding Pattern

### ISSUE THREAD

**Issue by nitishbhatia25** [Mittal-Analytics/Screener.in#33]
Add the feature for ShareHolding Pattern to track Promoter selling/buying activities.
A new Feature after Reports will show the Shareholding Pattern for the last 1,2,3,5 years.

**Comment by r0h1t123** [comment]
Sorry, I don't understand this (as a noob). The SHP is not showing up on my screens? Do I need to activate that somehow?

**Comment by nitishbhatia25** [comment]
Search for "Change in Promoter Holding" in Manage Quick Ratio to add that field.
The feature is already implemented , therefore closing this issue.
