### ISSUE TITLE
Data NAN issue

### ISSUE THREAD

**Issue by ThHarikishan** [Mittal-Analytics/Screener.in#37]
Hi Team,

Thanks a lot for developing Screener.in, which is extremely helpful for domestic indian investors like me. Recently there is NAN data displaying for many fields. Could you kindly look into it.

**Comment by imchess007** [comment]
Hi Team,

Recently there is NAN data displaying for many fields. Could you kindly look into it??

**Comment by pratyushmittal** [comment]
Fixed.

**Comment by ThHarikishan** [comment]
Thanks Pratyush.

**Comment by imchess007** [comment]
Thanks Pratyush!
