### ISSUE TITLE
Data for Stock P/E, Dividend Yield and some other fields is missing

### ISSUE THREAD

**Issue by enugalak** [Mittal-Analytics/Screener.in#38]
Hi Screener Team,

Looks like data for Stock P/E, Dividend Yield, Book Value, PEG Ratio, EPS preceding quarter, Expected quarterly EPS and Number of equity shares is missing. Can you please fix the issue?

Thanks a lot.
Kiran

**Comment by pratyushmittal** [comment]
Fixed.

**Comment by enugalak** [comment]
Thank you very much.
