### ISSUE TITLE
User Defined Ratio not available to create

### ISSUE THREAD

**Issue by networknetworks2012** [Mittal-Analytics/Screener.in#41]
Been a avid fan on screener.in, i thought to create some of the very important ratio/formulae for technical/fundamental analysis.
However, i didn't found any link for the same.
From the old blog, i found the url; but even that is not working..
Below is the URL

http://www.screener.in/create/ratio/

**Comment by pratyushmittal** [comment]
New ratios can be created at: https://www.screener.in/ratios/

This link is shown when we click "Customise columns" and select "Create new ratio"
