### ISSUE TITLE
Watchlist not accepting more than  172 companies 

### ISSUE THREAD

**Issue by sarwalr** [Mittal-Analytics/Screener.in#98]
Even though these companies have been added to Watchlist, the list is not showing anything beyond 172 companies. 
This glitch is new, as till two days ago, I was able to see all 202 companies in my watchlist. Now, no new additions get reflected, even though they show as added in Company screen.

Please resolve this glitch. Thanks for this excellent, Open Source Tool.

**Comment by sarwalr** [comment]
A correction. 
Some stocks are not getting reflected in Watchlist even after their selection from main menu, such as Abbot India, Amara Raja Batteries, Can Fin Homes, Chamanlal Sethia Exports, CUB, Cochin Shipyard, Cupid, DCB Bank, Deccan Cements, GIC Housing Fin, Hind.Copper, Hind.Zinc, IOL Chemicals, 
Magna Electrocas, Mahanagar Gas, Manappuram Fin, Nandan Denim, NILE, Nitin Spinners, PNB Gilts, PNB Housing, Sanofi India, Selan Expl. Tech, Sh.Pushkar Chem., Skipper, Sreeleathers, Tata Motors-DVR, TCI Express, The Byke Hospi., V-Guard Inds., Vivid Global, VRL Logistics, Websol Energy.

Others are, even beyond 172 list. So, problem in stock specific.
Hope for an early resolution.

**Comment by gopal1035** [comment]
Same issue, some companies are not showing on Watchlist. Please fix.

**Comment by himan02** [comment]
Many companies not coming in Screens. Page of those companies exist and is updated but on Screens after running the query, information of those is missing.

**Comment by pratyushmittal** [comment]
We have fixed it now.
